### ISSUE TITLE
Exception ignored in: <function SqliteDatabase.__del__ at 0x16C14100>

### ISSUE THREAD

**Issue by FoolingMyselfWithDreams** [Ben-0-mad/YT-TMS-Finder#5]
I got this error after about 2 hours of checking a very large channel:

sqlite - connection opened
Exception ignored in: <function SqliteDatabase.__ del __ at 0x16C14100>
Traceback (most recent call last):
File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)

This repeats for a while, then at the end:

self.__convertor.write(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 184, in write_and_convert
    text = self.convert_osc(text)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\colorama\ansitowin32.py", line 246, in convert_osc
    for match in self.ANSI_OSC_RE.finditer(text):
RecursionError: maximum recursion depth exceeded while calling a Python object
sqlite - connection has been closed

It then stops the program and puts me back on the cmd line.

**Comment by Ben-0-mad** [comment]
Seems there's definitely a problem with colorama (for colored text). I can try to catch the error but ultimately I'd like to completely get rid of these problems at the source. I will fix this tomorrow.

**Comment by Ben-0-mad** [comment]
Btw for convenience could you also tell me which youtube channel you were testing?

**Comment by Ben-0-mad** [comment]
Issue was fixed.

**Comment by Ben-0-mad** [comment]
not fixed

**Comment by Ben-0-mad** [comment]
Fixed. Fix will be in new version
